services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
        - "8080:8080"
    environment:
        SPRING_PROFILES_ACTIVE: local
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/shortener?currentSchema=shortener
    depends_on:
        postgresql:
          condition: service_healthy

  postgresql:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    healthcheck:
      test: [ "CMD", "psql", "postgresql://user:password@localhost:5432/shortener", "-c", "select 1;" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]